### ISSUE TITLE
Android In-App Review not working in Emulator and Real Device

### ISSUE THREAD

**Issue by Aravin** [britannio/in_app_review#12]
Hi Team,

This is my code, on button click

## Code
```
                final InAppReview inAppReview = InAppReview.instance;

                if (await inAppReview.isAvailable()) {
                  inAppReview.requestReview();
                } else {
                  inAppReview.openStoreListing();
                }
```

## Logs

```
I/InAppReviewPlugin( 1428): onComplete: Successfully requested review flow
I/flutter ( 1428): true
I/InAppReviewPlugin( 1428): isAvailable: called
I/InAppReviewPlugin( 1428): isAvailable: playStoreInstalled: true
I/InAppReviewPlugin( 1428): isAvailable:lollipopOrLater: true
I/InAppReviewPlugin( 1428): isAvailable: The Play Store is available and Android 5 or later is being used
I/InAppReviewPlugin( 1428): cacheReviewInfo: called
I/PlayCore( 1428): UID: [10351]  PID: [1428] ReviewService : requestInAppReview (io.epix.warranty_manager)
I/InAppReviewPlugin( 1428): cacheReviewInfo: Requesting review flow
I/PlayCore( 1428): UID: [10351]  PID: [1428] ReviewService : Initiate binding to the service.
I/PlayCore( 1428): UID: [10351]  PID: [1428] ReviewService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.inappreviewservice.InAppReviewService})
I/PlayCore( 1428): UID: [10351]  PID: [1428] ReviewService : linkToDeath
I/PlayCore( 1428): UID: [10351]  PID: [1428] OnRequestInstallCallback : onGetLaunchReviewFlowInfo

```

**Comment by britannio** [comment]
Looks similar to https://github.com/britannio/in_app_review/issues/2
1) Are you following https://github.com/britannio/in_app_review/tree/master/in_app_review#android-1 and testing your app from the Play Store?
2) `isAvailable()` can return true but it doesn't guarantee that `requestReview()` will display the review dialog as the [quota](https://developer.android.com/guide/playcore/in-app-review#quotas) may have been exceeded so it's not recommended to use `requestReview()` in response to a button being pressed. `openStoreListing()` should be used instead in such a scenario.

**Comment by britannio** [comment]
@Rob-rob-bot Are you running code equivalent to this?
```dart
import 'package:in_app_review/in_app_review.dart';

final InAppReview inAppReview = InAppReview.instance;

if (await inAppReview.isAvailable()) {
    inAppReview.requestReview();
}
```
If you are using `requestReview()` on a [compatible device](https://github.com/britannio/in_app_review/tree/master/in_app_review#android-1) and testing your app via internal app sharing then the review popup should appear every time.

**Comment by britannio** [comment]
>Shouldn't internal testing deliver the same results as the shortened app sharing flow?

It should be the same however I've only tested this via [internal app sharing](https://play.google.com/apps/publish/internalappsharing/) as it takes less time to setup.

**Comment by britannio** [comment]
@Rob-rob-bot Are you still facing any issues with this plugin?

**Comment by NicolasCELLA** [comment]
Hello, nothing happens with this code:
```
if (await _inAppReview.isAvailable()) {
        _inAppReview.requestReview()'
} else {
        if (Platform.isAndroid)
          _inAppReview.openStoreListing(appStoreId: ....);
        else
          _inAppReview.openStoreListing(appStoreId: ....);
}
```

Any idea ?

**Comment by Aravin** [comment]
@NicolasCELLA 

It should be working on the supported device.

This is my implementation

https://github.com/Aravin/WarrantyManager/blob/a4e6f9ed3dfa5fec9e8ddc075a48c3f3a3c841ab/lib/screens/home.dart#L108

This is my application

https://play.google.com/store/apps/details?id=io.epix.warranty_manager

Working fine.

**Comment by britannio** [comment]
@NicolasCELLA Can you confirm that you are following [the guidelines](https://github.com/britannio/in_app_review#guidelines)? There are also [testing instructions](https://github.com/britannio/in_app_review#testing).

If `_inAppReview.isAvailable()` returns `true`, it doesn't guarantee that the review prompt will be shown as the quota of the underlying API may have been exceeded. Because of this, it's advised to not use rely on `requestReview()` to let a user review your app as a result of a button being pressed.

Also, `_inAppReview.openStoreListing(appStoreId: ....);` works on Android, IOS, MacOS and Windows with a single call so you don't need to check if the platform is Android.

**Comment by tajaouart** [comment]
Same issue

**Comment by britannio** [comment]
> Same issue on real device (Samsung),
> The app is already published on playStore,
> only OpenStoreListing works

@tajaouart You've likely exceeded the quota on your device: https://developer.android.com/guide/playcore/in-app-review#quotas
If you'd still like to test out the pop up then install your app via [internal app sharing](https://play.google.com/console/u/0/internal-app-sharing).

**Comment by britannio** [comment]
@Aravin Are you still facing any issues with this plugin?

**Comment by tajaouart** [comment]
@Aravin 
It didn't even appear once so there is no problem related to quota...,
i want it to work not just to see it.

**Comment by britannio** [comment]
> @Aravin
> It didn't even appear once so there is no problem related to quota...,
> i want it to work not just to see it.

@tajaouart Did you install the app via internal app sharing?

**Comment by alex9153** [comment]
I have the same issue 

I/InAppReviewPlugin(20890): requestReview: called
I/PlayCore(20890): UID: [11467]  PID: [20890] ReviewService : requestInAppReview (app.....android)
I/InAppReviewPlugin(20890): requestReview: Requesting review flow
I/PlayCore(20890): UID: [11467]  PID: [20890] ReviewService : Initiate binding to the service.
I/PlayCore(20890): UID: [11467]  PID: [20890] ReviewService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.inappreviewservice.InAppReviewService})
I/PlayCore(20890): UID: [11467]  PID: [20890] ReviewService : linkToDeath
I/PlayCore(20890): UID: [11467]  PID: [20890] OnRequestInstallCallback : onGetLaunchReviewFlowInfo
I/PlayCore(20890): UID: [11467]  PID: [20890] ReviewService : Unbind from service.
I/InAppReviewPlugin(20890): onComplete: Successfully requested review flow
I/InAppReviewPlugin(20890): launchReviewFlow: called
W/ActivityThread(20890): handleWindowVisibility: no activity for token android.os.BinderProxy@38ce6f7
4
V/StudioTransport(20890): Handling agent command 1200 for pid: 20890.
W/JavaBinder(20890): BinderProxy is being destroyed but the application did not call unlinkToDeath to unlink all of its death recipients beforehand.  Releasing leaked death recipient: com.google.android.play.core.internal.ai
V/StudioTransport(20890): Handling agent command 1200 for pid: 20890.
I/chatty  (20890): uid=11467(app.....android) Thread-3 identical 2 lines
4
V/StudioTransport(20890): Handling agent command 1200 for pid: 20890.
W/ConnectionTracker(20890): Exception thrown while unbinding
W/ConnectionTracker(20890): java.lang.IllegalArgumentException: Service not registered: ls@7d23fda
W/ConnectionTracker(20890): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1562)
W/ConnectionTracker(20890): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1692)
W/ConnectionTracker(20890): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:717)
W/ConnectionTracker(20890): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204713067@20.47.13 (100408-0):1)
W/ConnectionTracker(20890): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204713067@20.47.13 (100408-0):2)
W/ConnectionTracker(20890): 	at lt.E(:com.google.android.gms.dynamite_measurementdynamite@204713067@20.47.13 (100408-0):9)
W/ConnectionTracker(20890): 	at ld.a(:com.google.android.gms.dynamite_measurementdynamite@204713067@20.47.13 (100408-0):3)
W/ConnectionTracker(20890): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204713067@20.47.13 (100408-0):3)
W/ConnectionTracker(20890): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
W/ConnectionTracker(20890): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

**Comment by britannio** [comment]
@alex9153 Are you following the testing instructions? https://github.com/britannio/in_app_review#android

**Comment by tajaouart** [comment]
@britannio 
No i did not  install the app via internal app sharing, the application is already published in PlayStore, so it is supposed to work right ?

**Comment by britannio** [comment]
> @britannio
> No i did not install the app via internal app sharing, the application is already published in PlayStore, so it is supposed to work right ?

If it works in internal app sharing then it will work when your app is published although the quota restrictions are enforced when you publish the app so I encourage you to first test your app via internal app sharing. If it still doesn't work then let me know.

**Comment by alex9153** [comment]
> @alex9153 Are you following the testing instructions? https://github.com/britannio/in_app_review#android

My app is live in the Google Play. When I call requestReview() nothing happens

**Comment by britannio** [comment]
> > @alex9153 Are you following the testing instructions? https://github.com/britannio/in_app_review#android
> 
> My app is live in the Google Play. When I call requestReview() nothing happens.
> Should I configure google play console or google developer console somehow ?

This will happen if the quota described [here](https://developer.android.com/guide/playcore/in-app-review#quotas) is exceeded. `requestReview()` isn't designed to show the pop up every time when you've installed the production version of your app. 

Let me know if you find the [usage instructions](https://github.com/britannio/in_app_review#usage) and [guidelines](https://github.com/britannio/in_app_review#guidelines) confusing.

**Comment by alex9153** [comment]
> This will happen if the quota described [here](https://developer.android.com/guide/playcore/in-app-review#quotas) is exceeded. `requestReview()`

I call isAvailable() before requestReview() it returns true and nothing happens.

**Comment by britannio** [comment]
> > This will happen if the quota described [here](https://developer.android.com/guide/playcore/in-app-review#quotas) is exceeded. `requestReview()`
> 
> I call isAvailable() before requestReview() it returns true and nothing happens.

`isAvailable()` only checks if the device supports `requestReview()` but doesn't guarantee that `requestReview()` will show the review pop up. Please follow the testing instructions, either [from the README](https://github.com/britannio/in_app_review#testing) or [from the underlying Android API](https://developer.android.com/guide/playcore/in-app-review/test). If you still can't get `requestReview()` to show the review dialog after installing the app via internal app sharing then let me know.

**Comment by britannio** [comment]
@NicolasCELLA @tajaouart @alex9153 Are any of you still facing issues with this plugin? I don't think that there is an issue with the plugin itself.

**Comment by RowanG1Bilue** [comment]
I am still having this issue. Did you get it resolved?

**Comment by britannio** [comment]
@RowanG1Bilue Are you following the exact testing instructions? https://github.com/britannio/in_app_review/tree/master/in_app_review#testing

**Comment by tajaouart** [comment]
2022 still having the issue, internal testing + production.
I did get the review view appear just one the first time.

**Comment by Waruna-Kaushalya** [comment]
@tajaouart  Yes, the review view will appear only once per phone, regardless of user review or not. Did you get a solution for this?

**Comment by Waruna-Kaushalya** [comment]
@tajaouart I got this from stackoverflow.  "To provide a great user experience, Google Play enforces a time-bound quota on how often a user can be shown the review dialog. Because of this quota, calling the launchReviewFlow method more than once during a short period of time (for example, less than a month) might not always display a dialog."
[https://stackoverflow.com/questions/70564280/in-app-review-popup-window-not-showing-again-once-not-now-is-pressed](https://stackoverflow.com/questions/70564280/in-app-review-popup-window-not-showing-again-once-not-now-is-pressed)

**Comment by britannio** [comment]
I am curious if this is a proguard issue and if https://github.com/britannio/in_app_review/issues/68#issuecomment-1250256853 fixes it.

**Comment by amcny** [comment]
> @NicolasCELLA
> 
> It should be working on the supported device.
> 
> This is my implementation
> 
> https://github.com/Aravin/WarrantyManager/blob/a4e6f9ed3dfa5fec9e8ddc075a48c3f3a3c841ab/lib/screens/home.dart#L108
> 
> This is my application
> 
> https://play.google.com/store/apps/details?id=io.epix.warranty_manager
> 
> Working fine.

how does it works. can you please explain your implementation. i didnt understand else condition, where you used  inAppReview.openStoreListing();
