### ISSUE TITLE
PlayCoreDialogWrapperActivity crash in library version 2.0.9

### ISSUE THREAD

**Issue by Jithin-Jude** [britannio/in_app_review#124]
Crash hapenning in Pixel 4a Android 12

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mountzoft.gameofzeros/com.google.android.play.core.common.PlayCoreDialogWrapperActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.os.BaseBundle.get(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by britannio** [comment]
That's an odd stack trace. Maybe https://github.com/jamesmontemagno/StoreReviewPlugin/issues/6#issuecomment-703158307 fixes the crash?

**Comment by Jithin-Jude** [comment]
Will try this if the crash happens again. Are you planing to update library?

**Comment by gazb23** [comment]
> Will try this if the crash happens again. Are you planing to update library?

Did you resolve this issue?

**Comment by chaobiaoZhang** [comment]
I also found the same problem in 2.0.8
[Uploading com.ho.app_issue_3dc8fa874f93d5b097d5f7ef49185fbb_crash_session_6713E3290386000178FD37E8DED7F413_DNE_0_v2_stacktrace.txt…]()

**Comment by Alex-collab-byte** [comment]
> Will try this if the crash happens again. Are you planing to update library?

Have you solved it yet
