### ISSUE TITLE
Calling requestReview(); not working in android internal app sharing

### ISSUE THREAD

**Issue by tytruong1608** [britannio/in_app_review#20]
I have up to internal testing, but it work when i call requestReview(), promt review never shown.

```
I InAppReviewPlugin: requestReview: called
I InAppReviewPlugin: launchReviewFlow: called
E ActivityTaskManager: intent received is not valid or null
I ActivityTaskManager: START u0 {cmp=com.offtherecord.otr_mobile_app/com.google.android.play.core.common.PlayCoreDialogWrapperActivity (has extras)} from uid 10467
E Parcel  : Class not found when unmarshalling: com.google.android.play.core.review.d
E Parcel  : java.lang.ClassNotFoundException: com.google.android.play.core.review.d
E Parcel  : 	at java.lang.Class.classForName(Native Method)
E Parcel  : 	at java.lang.Class.forName(Class.java:454)
E Parcel  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:3031)
E Parcel  : 	at android.os.Parcel.readParcelable(Parcel.java:2981)
E Parcel  : 	at android.os.Parcel.readValue(Parcel.java:2883)
E Parcel  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
E Parcel  : 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
E Parcel  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
E Parcel  : 	at android.os.BaseBundle.getString(BaseBundle.java:1160)
E Parcel  : 	at android.content.Intent.getStringExtra(Intent.java:8552)
E Parcel  : 	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:847)
E Parcel  : 	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:732)
E Parcel  : 	at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:2072)
E Parcel  : 	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:646)
E Parcel  : 	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1717)
E Parcel  : 	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1613)
E Parcel  : 	at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1566)
E Parcel  : 	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1746)
E Parcel  : 	at android.os.Binder.execTransactInternal(Binder.java:1056)
E Parcel  : 	at android.os.Binder.execTransact(Binder.java:1029)
E Parcel  : Caused by: java.lang.ClassNotFoundException: com.google.android.play.core.review.d
E Parcel  : 	... 20 more
W Bundle  : Failed to parse Bundle, but defusing quietly
W Bundle  : android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.google.android.play.core.review.d
W Bundle  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:3059)
W Bundle  : 	at android.os.Parcel.readParcelable(Parcel.java:2981)
W Bundle  : 	at android.os.Parcel.readValue(Parcel.java:2883)
W Bundle  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
W Bundle  : 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
W Bundle  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
W Bundle  : 	at android.os.BaseBundle.getString(BaseBundle.java:1160)
W Bundle  : 	at android.content.Intent.getStringExtra(Intent.java:8552)
W Bundle  : 	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:847)
W Bundle  : 	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:732)
W Bundle  : 	at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:2072)
W Bundle  : 	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:646)
W Bundle  : 	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1717)
W Bundle  : 	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1613)
W Bundle  : 	at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1566)
W Bundle  : 	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1746)
W Bundle  : 	at android.os.Binder.execTransactInternal(Binder.java:1056)
W Bundle  : 	at android.os.Binder.execTransact(Binder.java:1029)
```

Edit sorry should add flutter -v output

```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-US)
    • Flutter version 1.22.3 at /Users/macbook/Documents/development/flutter
    • Framework revision 8874f21e79 (2 months ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3
```

**Comment by britannio** [comment]
@tytruong1608  Were you using the internal testing track or [internal app sharing](https://play.google.com/apps/publish/internalappsharing/)?

**Comment by britannio** [comment]
@tytruong1608 Is this still an issue?

**Comment by darshakpranpariya** [comment]
I have already uploaded my app in playstore. Now i am integrating in_appreview in my app, but in debug mode requestReview() is not showing pop box. 
Please any help.

**Comment by britannio** [comment]
@darshakpranpariya Are you following the testing instructions at https://github.com/britannio/in_app_review#testing?

**Comment by darshakpranpariya** [comment]
Yes i have already added my email id in internal app sharing. Still pop is not opening.

**Comment by britannio** [comment]
@darshakpranpariya Are you testing the app you downloaded from the Play Store? It doesn't work when running the app locally in debug or release mode.

**Comment by darshakpranpariya** [comment]
No i am running app in debug mode. But Let me try, after releasing it on playstore and then download it from there, then i would check whether it's working or not.
Thanks for your frequent response 🙏

**Comment by Niravoo7** [comment]
@darshakpranpariya Have you got any response from release build on store?

**Comment by glosama** [comment]
> No i am running app in debug mode. But Let me try, after releasing it on playstore and then download it from there, then i would check whether it's working or not. Thanks for your frequent response 🙏

The same is happening with me also, I also uploaded a build on an Internal testing check in my Redmi device it's showing me a pop-up, but while my other developer is testing it, it's not showing on his Samsung device.
I don't understand the issue with the devices but if its working fine on Production release mode, let me know

**Comment by britannio** [comment]
Closing this as a stale issue. If you're still facing the issue, drop a comment and I'll reopen it.
